<?php

$helper = $this->helper('Hic\Integration\Helper\Helper');
?>
<?php if($helper->isEnabled()):?>

<script id="hiconversion_head_always" type="text/javascript">
    var __hic = __hic || {};
    (function(){
        try {
            __hic.version = "1.0.0";
            __hic.data = __hic.data || {};
            __hic.data.platform = "magento2";
            __hic.data.pid = "<?php echo $helper->getSiteId(); ?>";
            
            var script = document.createElement("script");
            script.id = "hiconversion_30";
            script.async = "async";
            script.type = "text/javascript";
            script.src = "//h30-deploy.hiconversion.com/origin/tag/<?php echo $helper->getSiteId(); ?>";
            var nodes = document.getElementsByTagName("script");
            if (nodes.length > 0) {
                nodes[0].parentNode.insertBefore(script, nodes[0]);
            }
        } catch (e) {
        }
    })();
</script>
<?php endif; ?>
